# このサイト全体のタイトル
site_name: 喜平 -静岡蔵謹醸- | 静岡平喜酒造株式会社

# meta description（og:description・twitter:descriptionでも使用）
description: 生まれの地 ”静岡” にて喜平は、新しく生まれ変わりました。

# meta keywords
keywords: []

# カノニカル・og:urlなどで使われる、このサイトのURL
# （複数ページあるサイトでは、全てに同じURLを入れないように）
url: http://shizuokahirakishuzo.com/

# Facebook OGP・Twitter cardsで使われる画像 フルURLで指定すること
ogp_image_url: http://shizuokahirakishuzo.com/ogp.jpg

# Facebookアプリのapp id（入れないとWarningが出る）
facebook_app_id: 268436903511178

# Twitter cardsの管理者として登録するアカウント（※任意）
# twitter_card_owner: '@TwitterJP'

# favicon
favicon_url: /favicon.ico

# サイトをホーム画面に追加した際のアイコン画像
# webclipicon_url: http://example.com/webclipicon.png

# iOSにて、サイトをホーム画面に追加した際の、ステータスバーの挙動指定
# ios_status_bar: default
